export const SUBGRAPH_URL = import.meta.env.VITE_SUBGRAPH_URL;

export const CONTRACT_ADDRESSES = {
  STREAK: import.meta.env.VITE_STREAK_ADDRESS,
  CLEANUP_FACTORY: import.meta.env.VITE_CLEANUP_FACTORY_ADDRESS,
  USER_REGISTRY: import.meta.env.VITE_USER_REGISTRY_ADDRESS,
  REWARDS_MANAGER: import.meta.env.VITE_REWARDS_MANAGER_ADDRESS,
  ADDRESSES_PROVIDER: import.meta.env.VITE_ADDRESSES_PROVIDER_ADDRESS,
} as const;

export const PAGE_SIZE = 50;
